version: 2

sources:
  - name: stitch_salesforce_crm
    database: "{{ var('stg_salesforce_crm_stitch_database') }}"
    schema: "{{ var('stg_salesforce_crm_stitch_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: _sdc_batched_at

    tables:
      - name: Account
      - name: Contact
      - name: Lead
      - name: OpportunityHistory
      - name: Opportunity
      - name: User
